# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81545a563078938ddc64b8edde2b23aed8715bb8195a179c2f6bc44cef0657486cab257283bd92109f0b03b96eaed9b922705a4d9546d1eca9e472ffb5c8ca45

test:
  secret_key_base: fcddd1775f62426f5e08e14c1ff2f8c7900079b34f457f5a85b1a0ebfd47919afa7f6d20d59fe48187d1c5433b7290968b598aee3d144cb16d50e72a9b42afce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
